### PR TITLE
Shame fixes

### PR DESCRIPTION
**Pull request by twisteddedication**
Hello! I was a big fan of the original AoG and was glad to see someone picked up development on it again. I ran into a softlock while playing and thought I'd do a little digging to see if I couldn't figure it out. I think I've fixed it and, hopefully, haven't broken anything else in the meantime.

The issue was, if you entered a map with an entrance to the Dali sewers as a nude, shy slave, Garnet would get stuck in an infinite loop of complaining about her state of undress. To fix this, I moved the shame checks to be part of the sewer exit events instead. In the process, I also fixed a couple other bugs around the shame system: shame should now be correctly checked when leaving combat, and an unrelated softlock that could occur when combat ends in the middle of a move while Garnet is shy and nude (caused by Blizz-ABS not "allowing idle" when the move is interrupted in this way).

I'm pretty new to RPGM, so let me know if I've done anything wrong! Thanks!

### CODE REVIEW

**Comment by twisteddedication** [comment]
Updated to fix a few other instances of this softlock I had missed before.

Oh, and for convenience because .rxdata files don't lend themselves to code review, here's a more detailed changelist:

Updated the following events to set both `0089: Nudity OK` and `0210: MapState:Battle` to OFF, as well as call the `Check Shame` common event:

- `swampsToSewers`: southern exit
- `sewer to jail`: northern exit
- `sewer to farm2`: western exit
- `sewer to Ren's home`: northern exit
- `stoneDoorDali`: Stone Door event page B
- `daliSewerWithGoblinWest1`: all eastern exits
- `bath in`: southwest exit (this one doesn't require a combat state update)

Deleted the autorun events spamming Check Shame every frame from the following maps:

- `swamps caves 01`
- `bath house`
- `Prison`
- `Ren Sisters Home`
- `Dali Farm [KTS]`
- `Goblin Cave - West 1`
- `White Tower[KTS]`

Added script `Blizz-ABS - allow idle on player` that forcefully sets `idle_allowed` on the player

Updated the Check Shame common event as follows:

- Fixed slave branch message grammar
- Rewrote non-slave nude shy branch to use the new `allow idle` script

Small change to Update Equipment common event to set the Update Equipment switch off *before* calling Check Shame (which may turn it back on)

Small change to MapState: Battle common event to use the control switch for Update Equipment rather than calling the event directly from a parallel event (as I understand, this can cause issues)

**Comment by taberenc** [comment]
hi.
thanks.
i got stuck in some things: 
- the enemy levels, equipment levels and garnet attack levels, that require since a lot of years ago to be recalibrated: i did some excel tables to organize this issue according to the levels of garnet.
- the graphic part, since there are not enough animations. i thought on using AI's, but got a bit stuck there trying to know and understand the tensor mechanics and where to do this kind of things.
- the end of the game: last thing was a level with some characters still to be developed in the hell area, the magic progress of garnet and the final boss and father rescue event.

I thank you that you have fixed this shame issue. i'll check what you have done as soon as i can.
the last one that came to help was working on a house in carthage, and in some way he gave me more job than help, but his intentions were good, i think. but then, as sudden as he came, he go away.
i need some time to prepare the things and have all the programs and time to begin to work with this again.

by now.. thanks, and ... ok, as soon as i can i'll check it out, and.. make me know which more bugs you find, and.. yea, i can add you as a collaborator or something, i dont remember all the details of how this work right now.

by now, thanks, and i hope that your fix will work and feel free to make me know whatever you think that is needed.

**Comment by taberenc** [comment]
ok, by now i've assigned you this task about this bug that you have mentioned.

**Comment by twisteddedication** [comment]
Great, thanks! I'll keep an eye out for updates on the ticket, no rush :) I have lots of great memories with this game, so when I saw the opportunity, I wanted to help out. Feel free to ask if you have any questions about the changes I've made.

**Comment by taberenc** [comment]
been busy. tomorrow sunday or next monday i'll check it out and mostly sure i'll add your debug to the game. is just a matter of having some free time to do it.
if you have something else to add, now it would be a good moment, i guess.

**Pull request merged**
