### PR TITLE
Update Map168.rxdata

### PR DESCRIPTION
**Pull request by Novae17**
Added boxes to jump over the fence and 3 nests to collect honey if Garnet has none already.

### CODE REVIEW

**Comment by taberenc** [comment]
I've checked it. Only asking: the option to jump over the fence, being on the farm side, is an action button.. that is not beside the boxes. what if the choice would be presented just as player touch? because i think that.. as it is, it could be a bit difficult to find by a player.
And.. aobut the side within the fence.. have you seen if the access to the boxes is easy? to jump again to the farm side, i mean.

beyond this two details.. i think that i like it. and the hives seem a good idea.

**Comment by Novae17** [comment]
I think if we placed a small shining dot to show it can be interacted with, it should fix the entire issue.
And yes, from the inside it's simple to interact with.
I preferred to not do it as 'player touch' since it's on the road and could be annoying.

**Comment by taberenc** [comment]
ok, i undestand that. If is the case, i can merge it now, edit it, put a yellow shining there which is deactivated after 1st use, and go ahead.
I'll note your apport on the changelog.

**Review by taberenc — APPROVED** [review]
seen the map. a shining for the first time will be added.

**Pull request merged**
